import { initializeApp } from "https://www.gstatic.com/firebasejs/12.4.0/firebase-app.js";
import { getAuth, onAuthStateChanged, signInWithEmailAndPassword, signOut } from "https://www.gstatic.com/firebasejs/12.4.0/firebase-auth.js";
import { getFirestore, doc, getDoc } from "https://www.gstatic.com/firebasejs/12.4.0/firebase-firestore.js";
import { firebaseConfig, supabaseConfig } from "./config.js?v=20261002-3";

const $=id=>document.getElementById(id);
const state={profile:null,bundle:null,page:"dashboard",demo:false,month:null,detail:null};
let auth=null,db=null;
const fb=initializeApp(firebaseConfig); auth=getAuth(fb); db=getFirestore(fb);

const menu=[
["dashboard","Dashboard"],["shipping","Pengiriman Surat"],["blanko","Blanko Tilang Terbit"],
["disputes","Pelanggaran Tersanggah"],["terminated","Pelanggaran Dihentikan"],["court","Persidangan"],
["new","Data Baru"],["history","Perpindahan Proses"],["analytics","Analitik ETLE"],
["vehicles","Profil Kendaraan"],["search","Pencarian Global"],["report","Laporan ETLE"]
];
const icons={dashboard:"⌂",shipping:"✉",blanko:"▣",disputes:"⚑",terminated:"⊘",court:"⚖",new:"+",history:"↻",analytics:"▥",vehicles:"▤",search:"⌕",report:"▧"};

const demo={
cases:[
{case_id:"demo-1",violation_id:"39567",ref_number:"516-FCBDC-S9319WI",tnkb:"S9319WI",no_registrasi:"516-FCBDC-S9319WI",jenis_pelanggaran:"DAYA ANGKUT",pasal:"Pasal 307",lokasi:"Jl. Raya Guyangan",tanggal_pelanggaran:"2026-09-19T14:09:00+07:00",status_etle:"TERTAGIH",status_bayar:"PAID",no_blanko:"AJ0001039",no_briva:"1682-DEMO-001",tanggal_blanko:"2026-09-20",tanggal_sidang:"2026-09-28",nama_pemilik:"PT MAJU JAYA LOGISTIK",first_seen_at:"2026-09-19T14:20:00+07:00"},
{case_id:"demo-2",violation_id:"57993",ref_number:"70F-F02B3-AD8020Y",tnkb:"AD8020Y",jenis_pelanggaran:"DAYA ANGKUT",pasal:"Pasal 307",lokasi:"Jl. Raya Guyangan",tanggal_pelanggaran:"2026-09-21T03:30:40+07:00",status_etle:"TERSANGGAH",status_bayar:"INQUIRY",nama_pemilik:"CV SUMBER REJEKI",first_seen_at:"2026-09-21T04:00:00+07:00"},
{case_id:"demo-3",violation_id:"48210",ref_number:"081-DC263-S8324NJ",tnkb:"S8324NJ",jenis_pelanggaran:"DOKUMEN",pasal:"Pasal 288",lokasi:"Jl. Raya Guyangan",tanggal_pelanggaran:"2026-09-17T09:12:00+07:00",status_etle:"DIHENTIKAN",nama_pemilik:"BUDI SANTOSO",first_seen_at:"2026-09-17T10:00:00+07:00"}],
shipping:[{shipping_id:"s1",case_id:"demo-1",ref_number:"516-FCBDC-S9319WI",tnkb:"S9319WI",tracking_number:"JNE123456",courier:"JNE",status:"Terkirim",printed_date:"2026-09-19",delivered_at:"2026-09-22T11:00:00+07:00"},{shipping_id:"s2",case_id:"demo-2",ref_number:"70F-F02B3-AD8020Y",tnkb:"AD8020Y",tracking_number:"JNE234567",courier:"JNE",status:"Dalam Proses Pengiriman",printed_date:"2026-09-21"}],
disputes:[{dispute_id:"d1",case_id:"demo-2",violation_id:"57993",status:"TERSANGGAH",confirmation_date:"2026-09-21T08:45:00+07:00",reason:"Masih tahap klarifikasi muatan"}],
terminated:[{terminated_id:"t1",case_id:"demo-3",ref_number:"081-DC263-S8324NJ",tnkb:"S8324NJ",status:"Dihentikan",reason:"KIR MASIH HIDUP & VALID",officer_name:"Petugas UPPKB",terminated_at:"2026-09-17"}],
courts:[{court_id:"c1",case_id:"demo-1",violation_id:"39567",tanggal_sidang:"2026-09-28",pengadilan:"Pengadilan Negeri Nganjuk",status_sidang:"COMPLETED"}],
offenders:[{offender_id:"o1",case_id:"demo-1",nama:"PAMBUDI",alamat:"Nganjuk",no_telp:"081234567890",email:"demo@example.com"}],
histories:[{history_id:"h1",case_id:"demo-1",event_type:"LETTER_PRINTED",event_time:"2026-09-19T15:00:00+07:00",title:"Surat tilang dicetak",source:"ETLE_SHIPPING"},{history_id:"h2",case_id:"demo-1",event_type:"BLANKO_ISSUED",event_time:"2026-09-20T09:00:00+07:00",title:"Blanko tilang diterbitkan",source:"ETLE_BLANKO"}],
syncLogs:[]
};

const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const norm=v=>String(v??"").trim().toLowerCase();
const ym=v=>{if(!v)return null;const m=String(v).match(/^(\d{4})-(\d{2})/);return m?m[1]+"-"+m[2]:null};
const monthName=v=>{if(!v)return"Semua Data";const [y,m]=v.split("-");return new Intl.DateTimeFormat("id-ID",{month:"long",year:"numeric"}).format(new Date(Number(y),Number(m)-1,1))};
const fmtDate=v=>{if(!v)return"-";const d=new Date(v);if(Number.isNaN(d.getTime()))return esc(v);return new Intl.DateTimeFormat("id-ID",{day:"2-digit",month:"short",year:"numeric",hour:String(v).includes("T")?"2-digit":undefined,minute:String(v).includes("T")?"2-digit":undefined,timeZone:"Asia/Jakarta"}).format(d)};
const money=v=>v==null||v===""?"-":"Rp "+new Intl.NumberFormat("id-ID",{maximumFractionDigits:0}).format(Number(v));
const caseById=id=>state.bundle?.cases.find(x=>x.case_id===id);
const perms=()=>{const r=(state.profile?.role||"").trim().toUpperCase();return{report:r==="ADMIN"||r==="WASATPEL",copyPhone:r==="ADMIN"||r==="WASATPEL",admin:r==="ADMIN"}};

function toast(msg){$("toast").textContent=msg;$("toast").classList.remove("hidden");setTimeout(()=>$("toast").classList.add("hidden"),2600)}
function setSync(t){$("syncState").textContent=t}
function showApp(){$("loginView").classList.add("hidden");$("appView").classList.remove("hidden");renderProfile();buildMonthOptions();openPage("dashboard")}
function showLogin(){$("appView").classList.add("hidden");$("loginView").classList.remove("hidden")}
function renderProfile(){const p=state.profile||{nama:"Preview Demo",role:"DEMO"};const photo=p.photoUrl?'<img class="profile-photo" src="'+esc(p.photoUrl)+'" alt="Foto profil">':'<div class="profile-fallback">'+esc((p.nama||"G")[0])+'</div>';$("profile").innerHTML='<div class="profile-card">'+photo+'<div class="profile"><b>'+esc(p.nama)+'</b><span>'+esc(p.role)+'</span></div></div>'}
function renderNav(){$("nav").innerHTML=menu.map(([id,t])=>'<button class="nav-btn '+(state.page===id?"active":"")+'" data-id="'+id+'"><span>'+icons[id]+'</span><span>'+t+'</span></button>').join("");$("nav").querySelectorAll("button").forEach(b=>b.onclick=()=>{document.querySelector(".sidebar").classList.remove("open");openPage(b.dataset.id)})}
function buildMonthOptions(){const b=state.bundle||demo;const all=[...b.cases.flatMap(x=>[ym(x.tanggal_pelanggaran),ym(x.tanggal_blanko),ym(x.first_seen_at)]),...b.shipping.map(x=>ym(x.printed_date)),...b.disputes.map(x=>ym(x.confirmation_date)),...b.terminated.map(x=>ym(x.terminated_at)),...b.courts.map(x=>ym(x.tanggal_sidang)),...b.histories.map(x=>ym(x.event_time))].filter(Boolean);const months=[...new Set(all)].sort().reverse();$("globalMonth").innerHTML='<option value="">Semua Data</option>'+months.map(m=>'<option value="'+m+'">'+monthName(m)+'</option>').join("");$("globalMonth").value=state.month||""}
$("globalMonth").onchange=e=>{state.month=e.target.value||null;renderPage()};

function openPage(p){state.page=p;renderNav();const names=Object.fromEntries(menu);$("pageTitle").textContent=names[p];$("pageSub").textContent=p==="dashboard"?"Monitoring ETLE terintegrasi":"Data G-Smart UPPKB Guyangan";if(p==="report"&&!perms().report){$("content").innerHTML='<div class="notice">Role Anda tidak memiliki akses ke Laporan ETLE.</div>';return}renderPage()}
function period(v){return !state.month||ym(v)===state.month}
function activeDisputes(b){const term=new Set(b.terminated.map(x=>x.case_id).filter(Boolean));return b.disputes.filter(x=>period(x.confirmation_date)&&x.case_id&&!term.has(x.case_id))}
function counts(b){return{
shipping:b.shipping.filter(x=>period(x.printed_date)).length,
blanko:b.cases.filter(x=>x.no_blanko&&period(x.tanggal_blanko)).length,
disputes:activeDisputes(b).length,
terminated:b.terminated.filter(x=>period(x.terminated_at)).length,
court:b.courts.filter(x=>period(x.tanggal_sidang)).length,
newData:b.cases.filter(x=>period(x.first_seen_at)).length,
transitions:new Set(b.histories.filter(x=>period(x.event_time)&&x.case_id).map(x=>x.case_id)).size,
total:b.cases.filter(x=>period(x.tanggal_pelanggaran)).length
}}
function filteredRows(page,b){switch(page){
case"shipping":return b.shipping.filter(x=>period(x.printed_date));
case"blanko":return b.cases.filter(x=>x.no_blanko&&period(x.tanggal_blanko));
case"disputes":return activeDisputes(b);
case"terminated":return b.terminated.filter(x=>period(x.terminated_at));
case"court":return b.courts.filter(x=>period(x.tanggal_sidang));
case"new":return b.cases.filter(x=>period(x.first_seen_at));
case"history":return b.histories.filter(x=>period(x.event_time));
default:return[]}}
function renderPage(){const b=state.bundle||demo;if(state.page==="dashboard")return dashboard(b);if(state.page==="analytics")return analytics(b);if(state.page==="vehicles")return vehicleProfiles(b);if(state.page==="search")return globalSearch(b);if(state.page==="report")return reportPage(b);return processPage(state.page,filteredRows(state.page,b))}

function dashboard(b){const c=counts(b);const cards=[["Total Perkara",c.total],["Pengiriman Surat",c.shipping],["Blanko Terbit",c.blanko],["Tersanggah",c.disputes],["Dihentikan",c.terminated],["Persidangan",c.court],["Data Baru",c.newData],["Perpindahan Proses",c.transitions]];const recent=b.cases.filter(x=>period(x.tanggal_pelanggaran)).sort((a,z)=>String(z.tanggal_pelanggaran).localeCompare(String(a.tanggal_pelanggaran))).slice(0,12);$("content").innerHTML='<div class="cards">'+cards.map(x=>'<div class="card"><div class="metric-label">'+x[0]+'</div><div class="metric-value">'+x[1]+'</div><div class="metric-note">'+monthName(state.month)+'</div></div>').join("")+'</div><div class="grid-2"><div class="panel"><div class="title-row"><h3>Perkara terbaru</h3><span class="badge">'+recent.length+' tampil</span></div>'+caseTable(recent)+'</div><div class="panel"><h3 class="section-heading">Status Pengiriman</h3>'+shippingSummary(b.shipping.filter(x=>period(x.printed_date)))+'</div></div>'}

function shipClass(v){switch(norm(v)){case"tercetak":return["Tercetak",""];case"dalam proses pengiriman":return["Dalam Proses","warn"];case"terkirim":return["Terkirim","success"];case"gagal kirim":return["Gagal Kirim","danger"];case"dikembalikan":return["Dikembalikan","orange"];default:return["Lainnya","gray"]}}
function shippingSummary(rows){const cats=["Tercetak","Dalam Proses","Terkirim","Gagal Kirim","Dikembalikan","Lainnya"];const map=Object.fromEntries(cats.map(x=>[x,0]));rows.forEach(r=>map[shipClass(r.status)[0]]++);return '<div class="status-grid">'+cats.map(k=>'<div class="status-card"><b>'+map[k]+'</b><span>'+k+'</span></div>').join("")+'</div>'}

function processPage(page,rows){const titles=Object.fromEntries(menu);let extra="";if(page==="shipping")extra='<select id="statusFilter"><option value="">Semua Status</option><option>Tercetak</option><option>Dalam Proses</option><option>Terkirim</option><option>Gagal Kirim</option><option>Dikembalikan</option><option>Lainnya</option></select>';$("content").innerHTML='<div class="panel"><div class="title-row"><h3>'+titles[page]+'</h3><span class="badge">'+rows.length+' data</span></div><div class="toolbar"><input id="filter" placeholder="Cari TNKB, nomor, status, pemilik...">'+extra+'</div><div id="slot">'+genericTable(page,rows)+'</div></div>';const apply=()=>{const q=norm($("filter").value);let r=rows.filter(x=>JSON.stringify(x).toLowerCase().includes(q));if(page==="shipping"&&$("statusFilter").value)r=r.filter(x=>shipClass(x.status)[0]===$("statusFilter").value);$("slot").innerHTML=genericTable(page,r);bindDetailRows()};$("filter").oninput=apply;if($("statusFilter"))$("statusFilter").onchange=apply;bindDetailRows()}
function rowCaseId(page,r){if(r.case_id)return r.case_id;if(page==="history")return r.case_id;return null}
function genericTable(page,rows){if(!rows.length)return'<div class="empty">Belum ada data pada periode ini.</div>';const defs={
shipping:[["tnkb","TNKB"],["tracking_number","No. Resi"],["courier","Kurir"],["status","Status"],["printed_date","Tgl Cetak"]],
blanko:[["tnkb","TNKB"],["jenis_pelanggaran","Jenis Pelanggaran"],["tanggal_blanko","Tgl Blanko"],["no_blanko","No. Blanko"],["no_briva","No. BRIVA"],["status_bayar","Status Bayar"]],
disputes:[["violation_id","Violation ID"],["status","Status"],["confirmation_type","Jenis Konfirmasi"],["confirmation_date","Tgl Konfirmasi"],["reason","Alasan"]],
terminated:[["tnkb","TNKB"],["status","Status"],["reason","Alasan"],["officer_name","Petugas"],["terminated_at","Tanggal"]],
court:[["violation_id","Violation ID"],["tanggal_sidang","Tgl Sidang"],["pengadilan","Pengadilan"],["status_sidang","Status"],["denda_putusan","Denda"]],
new:[["tnkb","TNKB"],["jenis_pelanggaran","Jenis Pelanggaran"],["tanggal_pelanggaran","Pelanggaran"],["first_seen_at","Pertama Masuk"],["status_etle","Status ETLE"]],
history:[["event_time","Waktu"],["event_type","Event"],["title","Judul"],["source","Sumber"]]
};const cols=defs[page]||[];return'<div class="table-wrap"><table class="data-table"><thead><tr>'+cols.map(c=>'<th>'+c[1]+'</th>').join("")+'</tr></thead><tbody>'+rows.map(r=>'<tr class="'+(rowCaseId(page,r)?"clickable":"")+'" data-case="'+esc(rowCaseId(page,r)||"")+'">'+cols.map(([k])=>'<td>'+cell(k,r[k])+'</td>').join("")+'</tr>').join("")+'</tbody></table></div>'}
function cell(k,v){if(k.includes("date")||k.includes("tanggal")||k.includes("time")||k==="first_seen_at"||k==="event_time"||k==="terminated_at")return fmtDate(v);if(k.includes("denda")||k.includes("amount"))return money(v);if(k==="status"){const c=shipClass(v);return'<span class="badge '+c[1]+'">'+esc(v||"-")+'</span>'}if(k.includes("status"))return'<span class="badge">'+esc(v||"-")+'</span>';return esc(v||"-")}
function caseTable(rows){if(!rows.length)return'<div class="empty">Belum ada perkara.</div>';const cols=[["tnkb","TNKB"],["jenis_pelanggaran","Jenis Pelanggaran"],["tanggal_pelanggaran","Tanggal Pelanggaran"],["status_etle","Status ETLE"],["no_blanko","No. Blanko"],["no_briva","No. BRIVA"],["nama_pemilik","Nama Pemilik"]];return'<div class="table-wrap"><table class="data-table"><thead><tr>'+cols.map(c=>'<th>'+c[1]+'</th>').join("")+'</tr></thead><tbody>'+rows.map(r=>'<tr class="clickable" data-case="'+esc(r.case_id)+'">'+cols.map(([k])=>'<td>'+cell(k,r[k])+'</td>').join("")+'</tr>').join("")+'</tbody></table></div>'}
function bindDetailRows(){document.querySelectorAll("[data-case]").forEach(r=>r.onclick=()=>r.dataset.case&&openDetail(r.dataset.case))}

function analytics(b){const cases=b.cases.filter(x=>period(x.tanggal_pelanggaran));const byTnkb={};const byOwner={};const byType={};cases.forEach(x=>{if(x.tnkb)byTnkb[norm(x.tnkb)]=(byTnkb[norm(x.tnkb)]||{label:x.tnkb,n:0}),byTnkb[norm(x.tnkb)].n++;if(x.nama_pemilik)byOwner[norm(x.nama_pemilik)]=(byOwner[norm(x.nama_pemilik)]||{label:x.nama_pemilik,n:0}),byOwner[norm(x.nama_pemilik)].n++;const t=x.jenis_pelanggaran||"LAINNYA";byType[t]=(byType[t]||0)+1});const rank=o=>Object.values(o).sort((a,z)=>z.n-a.n).slice(0,10);const type=Object.entries(byType).map(([label,n])=>({label,n})).sort((a,z)=>z.n-a.n);const repeat=Object.values(byTnkb).filter(x=>x.n>1).length;const c=counts(b);$("content").innerHTML='<div class="cards"><div class="card"><div class="metric-label">Total Pelanggaran</div><div class="metric-value">'+cases.length+'</div></div><div class="card"><div class="metric-label">TNKB Unik</div><div class="metric-value">'+Object.keys(byTnkb).length+'</div></div><div class="card"><div class="metric-label">Kendaraan >1 Perkara</div><div class="metric-value">'+repeat+'</div></div><div class="card"><div class="metric-label">Blanko Terbit</div><div class="metric-value">'+c.blanko+'</div></div></div><div class="grid-3"><div class="panel"><h3 class="section-heading">TNKB Terbanyak</h3>'+bars(rank(byTnkb))+'</div><div class="panel"><h3 class="section-heading">Pemilik Terbanyak</h3>'+bars(rank(byOwner))+'</div><div class="panel"><h3 class="section-heading">Jenis Pelanggaran</h3>'+bars(type.slice(0,10),true)+'</div></div>'}
function bars(rows,gold=false){if(!rows.length)return'<div class="empty">Belum ada data.</div>';const max=Math.max(...rows.map(x=>x.n),1);return'<div class="chart-list">'+rows.map(x=>'<div class="bar-row"><span class="bar-label" title="'+esc(x.label)+'">'+esc(x.label)+'</span><div class="bar-track"><div class="bar-fill '+(gold?"gold":"")+'" style="width:'+Math.max(3,x.n/max*100)+'%"></div></div><b>'+x.n+'</b></div>').join("")+'</div>'}

function vehicleProfiles(b){const groups={};b.cases.forEach(x=>{const k=norm(x.tnkb);if(!k)return;if(!groups[k])groups[k]={tnkb:x.tnkb,owner:x.nama_pemilik,count:0,latest:null,case_id:x.case_id};groups[k].count++;if(!groups[k].latest||String(x.tanggal_pelanggaran)>String(groups[k].latest))groups[k].latest=x.tanggal_pelanggaran,groups[k].case_id=x.case_id});const rows=Object.values(groups).sort((a,z)=>z.count-a.count);$("content").innerHTML='<div class="panel"><div class="title-row"><h3>Profil Kendaraan</h3><span class="badge">'+rows.length+' kendaraan</span></div><div class="toolbar"><input id="filter" placeholder="Cari TNKB atau pemilik..."></div><div id="slot">'+vehicleTable(rows)+'</div></div>';$("filter").oninput=e=>{$("slot").innerHTML=vehicleTable(rows.filter(r=>JSON.stringify(r).toLowerCase().includes(norm(e.target.value))));bindDetailRows()};bindDetailRows()}
function vehicleTable(rows){return'<div class="table-wrap"><table class="data-table"><thead><tr><th>TNKB</th><th>Nama Pemilik</th><th>Jumlah Perkara</th><th>Pelanggaran Terakhir</th></tr></thead><tbody>'+rows.map(r=>'<tr class="clickable" data-case="'+esc(r.case_id)+'"><td>'+esc(r.tnkb)+'</td><td>'+esc(r.owner||"-")+'</td><td>'+r.count+'</td><td>'+fmtDate(r.latest)+'</td></tr>').join("")+'</tbody></table></div>'}

function globalSearch(b){$("content").innerHTML='<div class="panel"><div class="title-row"><h3>Pencarian Global</h3></div><div class="toolbar"><input id="globalQuery" style="min-width:min(620px,100%)" placeholder="TNKB, No. Registrasi, Blanko, BRIVA, pemilik, nama pelanggar..."></div><div id="searchResult"><div class="empty">Masukkan minimal 2 karakter.</div></div></div>';$("globalQuery").oninput=e=>{const q=norm(e.target.value);if(q.length<2){$("searchResult").innerHTML='<div class="empty">Masukkan minimal 2 karakter.</div>';return}const offenderCase=new Map(b.offenders.map(o=>[o.case_id,o]));const rows=b.cases.filter(c=>JSON.stringify(c).toLowerCase().includes(q)||JSON.stringify(offenderCase.get(c.case_id)||{}).toLowerCase().includes(q)).slice(0,100);$("searchResult").innerHTML=caseTable(rows);bindDetailRows()}}
function reportSnapshot(b){const first={};b.histories.forEach(h=>{if(!h.case_id||!h.event_time)return;if(!first[h.case_id]||String(h.event_time)<String(first[h.case_id]))first[h.case_id]=h.event_time});const ids=Object.entries(first).filter(([,v])=>!state.month||ym(v)===state.month).map(([k])=>k);const set=new Set(ids);const blanko=new Set(b.cases.filter(x=>x.no_blanko).map(x=>x.case_id));const disputes=new Set(b.disputes.map(x=>x.case_id));const terminated=new Set(b.terminated.map(x=>x.case_id));const shipping=new Set(b.shipping.map(x=>x.case_id));const court=new Set(b.courts.map(x=>x.case_id));const success=ids.filter(id=>blanko.has(id)||disputes.has(id)||terminated.has(id));return{ids,total:ids.length,blanko:ids.filter(x=>blanko.has(x)).length,disputes:ids.filter(x=>disputes.has(x)).length,terminated:ids.filter(x=>terminated.has(x)).length,shipping:ids.filter(x=>shipping.has(x)).length,court:ids.filter(x=>court.has(x)).length,success:success.length,pending:ids.length-success.length}}
function reportText(s){const rate=s.total?s.success*100/s.total:0;const pending=s.total?s.pending*100/s.total:0;return 'LAPORAN ETLE UPPKB GUYANGAN\nPeriode: '+monthName(state.month)+'\n\nRingkasan ETLE\n• Total Perkara: '+s.total+'\n• Pengiriman Surat: '+s.shipping+'\n• Blanko Tilang: '+s.blanko+'\n• Tersanggah: '+s.disputes+'\n• Dihentikan: '+s.terminated+'\n• Persidangan: '+s.court+'\n\nSuccess Rate Konfirmasi Pelanggaran\n• Berhasil Konfirmasi: '+s.success+' dari '+s.total+' perkara\n• Success Rate: '+rate.toFixed(2)+'%\n• Belum Konfirmasi: '+s.pending+' perkara ('+pending.toFixed(2)+'%)\n\nSumber: G-SMART UPPKB Guyangan'}
function reportPage(b){const s=reportSnapshot(b);$("content").innerHTML='<div class="cards"><div class="card"><div class="metric-label">Total Perkara</div><div class="metric-value">'+s.total+'</div></div><div class="card"><div class="metric-label">Berhasil Konfirmasi</div><div class="metric-value">'+s.success+'</div></div><div class="card"><div class="metric-label">Belum Konfirmasi</div><div class="metric-value">'+s.pending+'</div></div><div class="card"><div class="metric-label">Success Rate</div><div class="metric-value">'+(s.total?s.success*100/s.total:0).toFixed(1)+'%</div></div></div><div class="panel"><div class="title-row"><h3>Laporan ETLE</h3><div class="action-row"><button id="copyReport" class="action-btn">Salin Ringkasan</button><button id="printReport" class="action-btn primary">Cetak / PDF</button></div></div><div class="report-summary">'+esc(reportText(s))+'</div></div>';$("copyReport").onclick=async()=>{await navigator.clipboard.writeText(reportText(s));toast("Ringkasan laporan disalin")};$("printReport").onclick=()=>window.print()}

async function q(table,{select="*",filters={},order=null,limit=1000}={}){const token=state.demo?null:await auth.currentUser.getIdToken(true);const u=new URL(supabaseConfig.url+"/rest/v1/"+table);u.searchParams.set("select",select);u.searchParams.set("limit",String(limit));if(order)u.searchParams.set("order",order);Object.entries(filters).forEach(([k,v])=>u.searchParams.set(k,v));const h={apikey:supabaseConfig.publishableKey};if(token)h.Authorization="Bearer "+token;const r=await fetch(u,{headers:h});if(!r.ok)throw new Error(table+" HTTP "+r.status);return r.json()}
async function write(table,body,{onConflict=null}={}){const token=await auth.currentUser.getIdToken(true);const u=new URL(supabaseConfig.url+"/rest/v1/"+table);if(onConflict)u.searchParams.set("on_conflict",onConflict);const r=await fetch(u,{method:"POST",headers:{apikey:supabaseConfig.publishableKey,Authorization:"Bearer "+token,"Content-Type":"application/json",Prefer:onConflict?"resolution=merge-duplicates,missing=default,return=minimal":"missing=default,return=minimal"},body:JSON.stringify(body)});if(!r.ok)throw new Error("Gagal menyimpan "+table+" (HTTP "+r.status+")")}

async function openDetail(caseId){$("modalBackdrop").classList.remove("hidden");$("modalBody").innerHTML='<div class="loading">Memuat detail perkara...</div>';const c=caseById(caseId);$("modalTitle").textContent="Detail Perkara";$("modalSubtitle").textContent=(c?.tnkb||"-")+" · "+(c?.ref_number||c?.no_registrasi||"");try{const d=state.demo?demoDetail(caseId):await loadDetail(caseId);state.detail=d;renderDetail(d)}catch(e){$("modalBody").innerHTML='<div class="notice">'+esc(e.message)+'</div>'}}
function demoDetail(id){const c=caseById(id)||demo.cases[0];return{case:c,offender:demo.offenders.find(x=>x.case_id===id),vehicle:{case_id:id,nama_pemilik:c.nama_pemilik,merk:"MITSUBISHI",tipe:"FUSO",jenis_kendaraan:"MOBIL BARANG",tahun_rakit:"2020",bahan_bakar:"SOLAR",jbb:3200,jbi:3100,berat_timbang:3450,berat_lebih:350},photos:[],shipping:demo.shipping.find(x=>x.case_id===id),payment:c.no_blanko?{no_briva:c.no_briva,status_bayar:c.status_bayar,titipan:500000,denda_maksimum:500000,denda_pengadilan:150000,biaya_perkara:5000,nominal_sisa:350000}:null,dispute:demo.disputes.find(x=>x.case_id===id),terminated:demo.terminated.find(x=>x.case_id===id),court:demo.courts.find(x=>x.case_id===id),manual:{kategori_internal:"BELUM_DIPROSES",prioritas:"NORMAL",catatan_ringkas:"Preview"},notes:[],history:demo.histories.filter(x=>x.case_id===id)}}
async function loadDetail(caseId){const c=caseById(caseId);if(!c)throw new Error("Perkara tidak ditemukan.");const one=async(t,f,v)=>{if(!v)return null;const r=await q(t,{filters:{[f]:"eq."+v},limit:1});return r[0]||null};const [offender,vehicle,photos,shipping,payment,dispute,terminated,court,manual,notes,history]=await Promise.all([
one("etle_offenders","case_id",caseId),one("etle_vehicles","case_id",caseId),q("etle_photos",{filters:{case_id:"eq."+caseId},order:"sort_order.asc"}),c.ref_number?one("etle_shipping","ref_number",c.ref_number):one("etle_shipping","case_id",caseId),one("etle_payments","case_id",caseId),c.violation_id?one("etle_disputes","violation_id",c.violation_id):one("etle_disputes","case_id",caseId),c.ref_number?one("etle_terminated_cases","ref_number",c.ref_number):one("etle_terminated_cases","case_id",caseId),c.violation_id?one("etle_court_info","violation_id",c.violation_id):one("etle_court_info","case_id",caseId),one("gsmart_case_status","case_id",caseId),q("gsmart_case_notes",{filters:{case_id:"eq."+caseId},order:"created_at.desc"}),q("gsmart_case_history",{filters:{case_id:"eq."+caseId},order:"event_time.desc.nullslast"})
]);return{case:c,offender,vehicle,photos,shipping,payment,dispute,terminated,court,manual,notes,history}}
function infoGrid(obj,fields){return'<div class="detail-grid">'+fields.filter(([k])=>obj&&obj[k]!=null&&obj[k]!=="").map(([k,l,t])=>'<div class="detail-item"><small>'+l+'</small><b>'+esc(t==="money"?money(obj[k]):t==="date"?fmtDate(obj[k]):obj[k])+'</b></div>').join("")+'</div>'}
function renderDetail(d){const p=perms();const c=d.case;const phone=d.offender?.no_telp;const phoneAction=p.copyPhone&&phone?'<button class="action-btn" id="copyPhone">Salin Telepon</button><button class="action-btn gold" id="waBtn">WhatsApp</button>':"";const photos=d.photos?.filter(x=>x.photo_url)||[];$("modalBody").innerHTML=
'<div class="action-row"><button class="action-btn primary" id="copyCase">Salin Ringkasan</button>'+phoneAction+'</div>'+
'<section class="detail-section"><h3 class="section-heading">Perkara</h3>'+infoGrid(c,[["tnkb","TNKB"],["no_registrasi","No. Registrasi"],["violation_id","Violation ID"],["jenis_pelanggaran","Jenis Pelanggaran"],["pasal","Pasal"],["lokasi","Lokasi"],["tanggal_pelanggaran","Tanggal Pelanggaran","date"],["status_etle","Status ETLE"],["no_blanko","No. Blanko"],["no_briva","No. BRIVA"]])+'</section>'+
'<section class="detail-section"><h3 class="section-heading">Pelanggar</h3>'+infoGrid(d.offender,[["nama","Nama"],["alamat","Alamat"],["no_telp","No. Telepon"],["email","Email"],["no_ktp","No. KTP"],["golongan_sim","Golongan SIM"],["tempat_lahir","Tempat Lahir"],["tanggal_lahir","Tanggal Lahir","date"],["pekerjaan","Pekerjaan"]])+'</section>'+
'<section class="detail-section"><h3 class="section-heading">Kendaraan</h3>'+infoGrid(d.vehicle,[["nama_pemilik","Nama Pemilik"],["alamat_pemilik","Alamat Pemilik"],["merk","Merk"],["tipe","Tipe"],["jenis_kendaraan","Jenis Kendaraan"],["tahun_rakit","Tahun"],["bahan_bakar","Bahan Bakar"],["no_uji","No. Uji"],["masa_berlaku_kir","Masa Berlaku KIR","date"],["jbb","JBB"],["jbi","JBI"],["berat_timbang","Berat Timbang"],["berat_lebih","Berat Lebih"]])+'</section>'+
(photos.length?'<section class="detail-section"><h3 class="section-heading">Foto ETLE</h3><div class="photo-grid">'+photos.map(x=>'<img src="'+esc(x.photo_url)+'" alt="'+esc(x.description||x.photo_type||"Foto ETLE")+'">').join("")+'</div></section>':"")+
'<div class="grid-2"><section class="detail-section"><h3 class="section-heading">Pengiriman</h3>'+infoGrid(d.shipping,[["tracking_number","No. Resi"],["courier","Kurir"],["status","Status"],["status_description","Keterangan"],["printed_date","Tanggal Cetak","date"],["delivered_at","Terkirim","date"]])+'</section><section class="detail-section"><h3 class="section-heading">Pembayaran</h3>'+infoGrid(d.payment,[["no_briva","No. BRIVA"],["status_bayar","Status Bayar"],["titipan","Titipan","money"],["denda_maksimum","Denda Maksimum","money"],["denda_pengadilan","Denda Pengadilan","money"],["biaya_perkara","Biaya Perkara","money"],["nominal_sisa","Sisa","money"],["paid_at","Dibayar","date"]])+'</section></div>'+
'<div class="grid-2"><section class="detail-section"><h3 class="section-heading">Sanggah / Dihentikan</h3>'+infoGrid(d.dispute,[["status","Status Sanggah"],["confirmation_date","Tanggal","date"],["reason","Alasan"],["result","Hasil"]])+infoGrid(d.terminated,[["status","Status Dihentikan"],["reason","Alasan"],["officer_name","Petugas"],["terminated_at","Tanggal","date"]])+'</section><section class="detail-section"><h3 class="section-heading">Persidangan</h3>'+infoGrid(d.court,[["tanggal_sidang","Tanggal Sidang","date"],["pengadilan","Pengadilan"],["hakim","Hakim"],["no_amar_putusan","Amar Putusan"],["denda_putusan","Denda Putusan","money"],["biaya_perkara","Biaya Perkara","money"],["status_sidang","Status"]])+'</section></div>'+
manualSection(d)+notesSection(d)+timelineSection(d.history||[]);
if($("copyPhone"))$("copyPhone").onclick=async()=>{await navigator.clipboard.writeText(phone);toast("Nomor telepon disalin")};
if($("waBtn"))$("waBtn").onclick=()=>openWhatsApp(d);
$("copyCase").onclick=async()=>{await navigator.clipboard.writeText("TNKB: "+(c.tnkb||"-")+"\nNo. Registrasi: "+(c.no_registrasi||"-")+"\nJenis Pelanggaran: "+(c.jenis_pelanggaran||"-")+"\nNo. Blanko: "+(c.no_blanko||"-")+"\nBRIVA: "+(c.no_briva||"-"));toast("Ringkasan perkara disalin")};
bindDetailActions(d)}
function manualSection(d){const m=d.manual||{};if(!perms().admin)return'<section class="detail-section"><h3 class="section-heading">Status Manual G-Smart</h3>'+infoGrid(m,[["kategori_internal","Kategori"],["prioritas","Prioritas"],["status_lebih_bayar","Status Lebih Bayar"],["nominal_lebih_bayar","Nominal Lebih Bayar","money"],["status_pengembalian","Status Pengembalian"],["pic_name","PIC"],["catatan_ringkas","Catatan"]])+'</section>';return'<section class="detail-section"><h3 class="section-heading">Status Manual G-Smart</h3><div class="form-grid"><label>Kategori<select id="manualCategory"><option>BELUM_DIPROSES</option><option>SUDAH_DIKONFIRMASI</option><option>SIAP_SIDANG</option><option>SELESAI</option></select></label><label>Prioritas<select id="manualPriority"><option>NORMAL</option><option>TINGGI</option><option>URGENT</option></select></label><label>Status Lebih Bayar<input id="overStatus" value="'+esc(m.status_lebih_bayar||"")+'"></label><label>Nominal Lebih Bayar<input id="overAmount" type="number" min="0" value="'+esc(m.nominal_lebih_bayar||"")+'"></label><label>Status Pengembalian<input id="refundStatus" value="'+esc(m.status_pengembalian||"")+'"></label><label class="full">Catatan<textarea id="manualNote" rows="3">'+esc(m.catatan_ringkas||"")+'</textarea></label><div class="full"><button id="saveManual" class="primary-btn">Simpan Status G-Smart</button></div></div></section>'}
function notesSection(d){return'<section class="detail-section"><h3 class="section-heading">Catatan Petugas</h3><div class="form-grid"><label class="full">Tambah Catatan<textarea id="newNote" rows="2" placeholder="Tulis catatan petugas..."></textarea></label><div class="full"><button id="addNote" class="action-btn primary">Tambah Catatan</button></div></div><div class="timeline" style="margin-top:14px">'+(d.notes?.length?d.notes.map(n=>'<div class="timeline-item"><b>'+esc(n.created_by_name||"Petugas")+'</b><span>'+esc(n.note)+'</span><small>'+fmtDate(n.created_at)+'</small></div>').join(""):'<div class="empty">Belum ada catatan.</div>')+'</div></section>'}
function timelineSection(rows){return'<section class="detail-section"><h3 class="section-heading">Timeline Perkara</h3><div class="timeline">'+(rows.length?rows.map(h=>'<div class="timeline-item"><b>'+esc(h.title||h.event_type)+'</b><span>'+esc(h.description||h.source||"")+'</span><small>'+fmtDate(h.event_time)+'</small></div>').join(""):'<div class="empty">Belum ada riwayat.</div>')+'</div></section>'}
function bindDetailActions(d){if($("manualCategory"))$("manualCategory").value=d.manual?.kategori_internal||"BELUM_DIPROSES";if($("manualPriority"))$("manualPriority").value=d.manual?.prioritas||"NORMAL";if($("saveManual"))$("saveManual").onclick=async()=>{try{setSync("Menyimpan");await write("gsmart_case_status",{case_id:d.case.case_id,kategori_internal:$("manualCategory").value,prioritas:$("manualPriority").value,status_lebih_bayar:$("overStatus").value||null,nominal_lebih_bayar:$("overAmount").value?Number($("overAmount").value):null,status_pengembalian:$("refundStatus").value||null,catatan_ringkas:$("manualNote").value||null,pic_uid:state.profile.uid,pic_name:state.profile.nama,updated_by:state.profile.uid},{onConflict:"case_id"});toast("Status G-Smart disimpan");await refreshDetail()}catch(e){toast(e.message)}finally{setSync("Siap")}};if($("addNote"))$("addNote").onclick=async()=>{const note=$("newNote").value.trim();if(!note)return;try{await write("gsmart_case_notes",{case_id:d.case.case_id,note,created_by:state.profile.uid,created_by_name:state.profile.nama});toast("Catatan ditambahkan");await refreshDetail()}catch(e){toast(e.message)}}}
async function refreshDetail(){const id=state.detail.case.case_id;state.detail=await loadDetail(id);renderDetail(state.detail)}
function openWhatsApp(d){const phone=normalizePhone(d.offender?.no_telp);if(!phone){toast("Nomor WhatsApp tidak valid");return}const c=d.case;const msg="Yth. Bapak/Ibu,\n\nKami dari Response Center ETLE Hub UPPKB Guyangan ingin mengonfirmasi terkait pelanggaran "+(c.jenis_pelanggaran||"ETLE")+" untuk kendaraan:\n\nNo. Polisi: "+(c.tnkb||"-")+"\n\nMohon konfirmasinya agar dapat kami lakukan pengecekan lebih lanjut pada sistem.\n\nTerima kasih.\n\nResponse Center ETLE Hub UPPKB Guyangan";window.open("https://wa.me/"+phone+"?text="+encodeURIComponent(msg),"_blank")}
function normalizePhone(v){const d=String(v||"").replace(/\D/g,"");if(d.startsWith("08"))return"62"+d.slice(1);if(d.startsWith("628"))return d;return null}
$("closeModal").onclick=()=>$("modalBackdrop").classList.add("hidden");
$("modalBackdrop").onclick=e=>{if(e.target===$("modalBackdrop"))$("modalBackdrop").classList.add("hidden")};

async function loadProfile(user){const s=await getDoc(doc(db,"users",user.uid));if(!s.exists())throw new Error("Profil petugas belum terdaftar.");const p=s.data();if(p.aktif!==true)throw new Error("Akun Anda tidak aktif.");return{uid:user.uid,nama:p.nama||p.username||user.email,nip:p.nip||"",username:p.username||user.email,role:p.role||"USER",photoUrl:p.photoUrl||null}}
async function loadDashboard(){setSync("Sinkronisasi");const [cases,shipping,disputes,terminated,courts,offenders,histories,syncLogs]=await Promise.all([q("etle_cases",{order:"tanggal_pelanggaran.desc.nullslast"}),q("etle_shipping",{order:"printed_date.desc.nullslast"}),q("etle_disputes",{order:"confirmation_date.desc.nullslast"}),q("etle_terminated_cases",{order:"terminated_at.desc.nullslast"}),q("etle_court_info",{order:"tanggal_sidang.desc.nullslast"}),q("etle_offenders"),q("gsmart_case_history",{order:"event_time.desc.nullslast"}),q("gsmart_sync_log",{order:"started_at.desc",limit:30})]);state.bundle={cases,shipping,disputes,terminated,courts,offenders,histories,syncLogs};setSync("Siap")}
$("loginForm").onsubmit=async e=>{e.preventDefault();$("loginMessage").textContent="Memverifikasi akun...";try{const c=await signInWithEmailAndPassword(auth,$("email").value.trim(),$("password").value);state.profile=await loadProfile(c.user);state.demo=false;await loadDashboard();$("loginMessage").textContent="";showApp()}catch(err){$("loginMessage").textContent=err.message||"Login gagal."}}
$("demoBtn").onclick=()=>{state.demo=true;state.profile={uid:"demo",nama:"Preview Demo",role:"ADMIN"};state.bundle=demo;showApp()}
$("logoutBtn").onclick=async()=>{state.profile=null;state.bundle=null;state.demo=false;state.month=null;await signOut(auth);showLogin()}
$("menuBtn").onclick=()=>document.querySelector(".sidebar").classList.toggle("open");
onAuthStateChanged(auth,async u=>{if(!u||state.demo)return;try{state.profile=await loadProfile(u);await loadDashboard();showApp()}catch(e){console.error(e);await signOut(auth);showLogin()}})
