import { initializeApp } from "https://www.gstatic.com/firebasejs/12.4.0/firebase-app.js";
import { getAuth, onAuthStateChanged, signInWithEmailAndPassword, signOut } from "https://www.gstatic.com/firebasejs/12.4.0/firebase-auth.js";
import { getFirestore, doc, getDoc } from "https://www.gstatic.com/firebasejs/12.4.0/firebase-firestore.js";
import { firebaseConfig, supabaseConfig } from "./config.js";

const $=id=>document.getElementById(id);
const state={profile:null,bundle:null,page:"dashboard",demo:false};
let auth=null,db=null;
const firebaseReady=Boolean(firebaseConfig.apiKey&&firebaseConfig.projectId);
if(firebaseReady){const fb=initializeApp(firebaseConfig);auth=getAuth(fb);db=getFirestore(fb)}

const menu=[["dashboard","Dashboard"],["shipping","Pengiriman Surat"],["blanko","Blanko Tilang Terbit"],["disputes","Pelanggaran Tersanggah"],["terminated","Pelanggaran Dihentikan"],["court","Persidangan"],["new","Data Baru"],["history","Perpindahan Proses"],["analytics","Analitik ETLE"],["vehicles","Profil Kendaraan"],["search","Pencarian Global"],["report","Laporan ETLE"]];
const demo={cases:[{tnkb:"S 9319 WI",jenis_pelanggaran:"DAYA ANGKUT",tanggal_pelanggaran:"2026-09-19",no_blanko:"AJ0001039",no_briva:"1682-DEMO-001",status_bayar:"PAID",nama_pemilik:"PT MAJU JAYA LOGISTIK",status_etle:"TERTAGIH"},{tnkb:"AD 8020 Y",jenis_pelanggaran:"DAYA ANGKUT",tanggal_pelanggaran:"2026-09-21",nama_pemilik:"CV SUMBER REJEKI",status_etle:"TERSANGGAH"},{tnkb:"S 8324 NJ",jenis_pelanggaran:"DOKUMEN",tanggal_pelanggaran:"2026-09-17",nama_pemilik:"BUDI SANTOSO",status_etle:"DIHENTIKAN"}],shipping:[{tnkb:"S 9319 WI",tracking_number:"JNE123456",status:"Terkirim"},{tnkb:"AD 8020 Y",tracking_number:"JNE234567",status:"Dalam Proses Pengiriman"}],disputes:[{status:"TERSANGGAH",case_id:"demo-2"}],terminated:[{tnkb:"S 8324 NJ",status:"Dihentikan",reason:"KIR masih hidup & valid"}],courts:[{tanggal_sidang:"2026-09-25",pengadilan:"Pengadilan Negeri Nganjuk",status_sidang:"COMPLETED"}],histories:[{event_time:"2026-09-20",title:"Blanko tilang diterbitkan",source:"ETLE_BLANKO"}],offenders:[],syncLogs:[]};

function perms(){const r=(state.profile?.role||"").trim().toUpperCase();return{report:r==="ADMIN"||r==="WASATPEL"}}
function showApp(){$("loginView").classList.add("hidden");$("appView").classList.remove("hidden");renderNav();renderProfile();openPage("dashboard")}
function showLogin(){$("appView").classList.add("hidden");$("loginView").classList.remove("hidden")}
function renderNav(){$("nav").innerHTML=menu.map(([id,t])=>`<button class="nav-btn ${state.page===id?"active":""}" data-id="${id}">${t}</button>`).join("");$("nav").querySelectorAll("button").forEach(b=>b.onclick=()=>openPage(b.dataset.id))}
function renderProfile(){const p=state.profile||{nama:"Preview Demo",role:"DEMO"};$("profile").innerHTML=`<div class="profile"><b>${p.nama}</b><span>${p.role}</span></div>`}
function openPage(p){state.page=p;renderNav();const names=Object.fromEntries(menu);$("pageTitle").textContent=names[p];$("pageSub").textContent=p==="dashboard"?"Monitoring ETLE terintegrasi":"Data G-Smart UPPKB Guyangan";if(p==="report"&&!perms().report){$("content").innerHTML='<div class="notice">Role Anda tidak memiliki akses ke Laporan ETLE.</div>';return}renderPage()}
function renderPage(){const b=state.bundle||demo;if(state.page==="dashboard")return dashboard(b);if(state.page==="analytics")return analytics(b);const map={shipping:["Pengiriman Surat",b.shipping],blanko:["Blanko Tilang Terbit",b.cases.filter(x=>x.no_blanko)],disputes:["Pelanggaran Tersanggah",b.disputes],terminated:["Pelanggaran Dihentikan",b.terminated],court:["Persidangan",b.courts],new:["Data Baru",b.cases],history:["Perpindahan Proses",b.histories],vehicles:["Profil Kendaraan",b.cases],search:["Pencarian Global",b.cases],report:["Laporan ETLE",b.cases]};const [title,rows]=map[state.page];tablePage(title,rows)}
function dashboard(b){const cards=[["Total Perkara",b.cases.length],["Pengiriman Surat",b.shipping.length],["Blanko Terbit",b.cases.filter(x=>x.no_blanko).length],["Tersanggah",b.disputes.length],["Dihentikan",b.terminated.length],["Persidangan",b.courts.length],["Data Baru",b.cases.length],["Timeline",b.histories.length]];$("content").innerHTML=`${(!firebaseReady||!supabaseConfig.url)?'<div class="notice">Web V1 aktif dalam mode preview. Firebase/Supabase Web belum diisi di config.js.</div>':""}<div class="cards">${cards.map(c=>`<div class="card"><div class="metric-label">${c[0]}</div><div class="metric-value">${c[1]}</div></div>`).join("")}</div><div class="panel"><div class="title-row"><h3>Perkara terbaru</h3><span class="badge">${b.cases.length} data</span></div>${tableHtml(b.cases)}</div>`}
function analytics(b){const unique=new Set(b.cases.map(x=>x.tnkb).filter(Boolean)).size;$("content").innerHTML=`<div class="cards"><div class="card"><div class="metric-label">Total Pelanggaran</div><div class="metric-value">${b.cases.length}</div></div><div class="card"><div class="metric-label">TNKB Unik</div><div class="metric-value">${unique}</div></div><div class="card"><div class="metric-label">Blanko</div><div class="metric-value">${b.cases.filter(x=>x.no_blanko).length}</div></div><div class="card"><div class="metric-label">Tersanggah</div><div class="metric-value">${b.disputes.length}</div></div></div>`}
function tablePage(title,rows){$("content").innerHTML=`<div class="panel"><div class="title-row"><h3>${title}</h3><span class="badge">${rows.length} data</span></div><div class="toolbar"><input id="filter" placeholder="Cari TNKB, status, pemilik..."></div><div id="slot">${tableHtml(rows)}</div></div>`;$("filter").oninput=e=>{const q=e.target.value.toLowerCase();$("slot").innerHTML=tableHtml(rows.filter(r=>JSON.stringify(r).toLowerCase().includes(q)))}}
function tableHtml(rows){if(!rows.length)return "<p>Belum ada data.</p>";const order=["tnkb","jenis_pelanggaran","tanggal_pelanggaran","status_etle","status","no_blanko","no_briva","tracking_number","nama_pemilik","tanggal_sidang","pengadilan","title"];const keys=order.filter(k=>rows.some(r=>k in r)).slice(0,7);return `<div class="table-wrap"><table class="data-table"><thead><tr>${keys.map(k=>`<th>${k.replaceAll("_"," ")}</th>`).join("")}</tr></thead><tbody>${rows.map(r=>`<tr>${keys.map(k=>`<td>${r[k]??"-"}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`}
async function profile(user){const s=await getDoc(doc(db,"users",user.uid));if(!s.exists())throw new Error("Profil petugas belum terdaftar.");const p=s.data();if(p.aktif!==true)throw new Error("Akun tidak aktif.");return{uid:user.uid,nama:p.nama||p.username||user.email,role:p.role||"USER"}}
async function loadData(user){if(!supabaseConfig.url||!supabaseConfig.publishableKey){state.bundle=demo;return}const token=await user.getIdToken(true);const h={apikey:supabaseConfig.publishableKey,Authorization:`Bearer ${token}`};async function q(t){const r=await fetch(`${supabaseConfig.url}/rest/v1/${t}?select=*`,{headers:h});if(!r.ok)throw new Error(`${t} HTTP ${r.status}`);return r.json()}const [cases,shipping,disputes,terminated,courts,offenders,histories,syncLogs]=await Promise.all([q("etle_cases"),q("etle_shipping"),q("etle_disputes"),q("etle_terminated_cases"),q("etle_court_info"),q("etle_offenders"),q("gsmart_case_history"),q("gsmart_sync_log")]);state.bundle={cases,shipping,disputes,terminated,courts,offenders,histories,syncLogs}}
$("loginForm").onsubmit=async e=>{e.preventDefault();if(!firebaseReady){$("loginMessage").textContent="Firebase Web belum dikonfigurasi. Gunakan Preview dulu.";return}try{const c=await signInWithEmailAndPassword(auth,$("email").value.trim(),$("password").value);state.profile=await profile(c.user);state.demo=false;await loadData(c.user);showApp()}catch(err){$("loginMessage").textContent=err.message||"Login gagal."}}
$("demoBtn").onclick=()=>{state.demo=true;state.profile={nama:"Preview Demo",role:"DEMO"};state.bundle=demo;showApp()}
$("logoutBtn").onclick=async()=>{if(auth)await signOut(auth);state.profile=null;state.bundle=null;state.demo=false;showLogin()}
$("menuBtn").onclick=()=>document.querySelector(".sidebar").classList.toggle("open");
if(auth)onAuthStateChanged(auth,async u=>{if(!u||state.demo)return;try{state.profile=await profile(u);await loadData(u);showApp()}catch{await signOut(auth);showLogin()}})
